sonar.projectKey=cfsalinasr_spps-assistant
sonar.organization=cfsalinasr

sonar.projectName=SPPS Synthesis Assistant
sonar.projectVersion=1.0.0

sonar.sources=spps_assistant
sonar.tests=tests
sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

sonar.sourceEncoding=UTF-8

# Exclude generated/infra files from duplication checks
sonar.cpd.exclusions=spps_assistant/infrastructure/pdf_generator.py,spps_assistant/infrastructure/docx_generator.py

# Exclude egg-info and cache
sonar.exclusions=**/*.egg-info/**,**/__pycache__/**,**/.*/**
